### ISSUE TITLE
[lacerdar] Automation exercise

### ISSUE THREAD

**Issue by iatzak** [Simulation-Software-Engineering/automation-exercise-wt2223#13]
[GitHub repository](https://github.com/iatzak/automation-exercise)

I also did the Gitlab task:
- Firstly, I converted the yaml file to Gitlab's standards, based on the [slides](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/05_testing_and_ci/gitlab_ci_slides.md) and the [`.gitlab-ci.yml` keyword reference](https://docs.gitlab.com/ee/ci/yaml/index.html).
- Then, I created a key pair with `ssh-keygen -t rsa -f cloud.key` and imported it to the "Key Pairs" section of the BW-cloud system.
- When creating an instance, I went for Ubuntu 22.04 and the m1.tiny flavor. The m1.small already required more RAM than my quota allowed.
- After launching the instance, I copied its IP adress and accessed it via `ssh ubuntu@[IP]`
- After running the commands from the [demo](https://github.com/Simulation-Software-Engineering/Lecture-Material/blob/main/05_testing_and_ci/gitlab_ci_demo.md), the `config.toml` file was placed inside `/srv/gitlab-runner/config/` and the pipeline ran in Gitlab.

You should already have access to [my Gitlab repo](https://gitlab-sim.informatik.uni-stuttgart.de/lacerdar/automation-exercise); let me know if that's not the case :)

**Comment by uekerman** [comment]
Looks good :+1:

Minor: `.gitignore` is in wrong place (on GitHub), needs to be at the root as the tests are called from there
