### ISSUE TITLE
[tuyetltg] Automation exercise

### ISSUE THREAD

**Issue by PommesFrittes** [Simulation-Software-Engineering/automation-exercise-wt2223#15]
GitHub:
[https://github.com/PommesFrittes/automation-exercise](https://github.com/PommesFrittes/automation-exercise)
GitLab:
[https://gitlab-sim.informatik.uni-stuttgart.de/tuyetltg/automation-exercise](https://gitlab-sim.informatik.uni-stuttgart.de/tuyetltg/automation-exercise)

**Comment by uekerman** [comment]
Looks good :+1:
