### ISSUE TITLE
[bergdoaa] Automation exercise

### ISSUE THREAD

**Issue by bergdola** [Simulation-Software-Engineering/automation-exercise-wt2223#23]
[GitHub repository bergdoaa](https://github.com/bergdola/automation-exercise-wt2223)

**Comment by uekerman** [comment]
Looks good, but don't create the `.gititgnore` file within your CI. Then, it is only temporary and doesn't serve any purpose. You need to add and commit it to the repository instead to make a difference.

**Comment by uekerman** [comment]
Also: 
- `black .`  directly formats. Use `black --check .` to only check the formatting.
