### ISSUE TITLE
[cevikma] Automation exercise

### ISSUE THREAD

**Issue by musteng** [Simulation-Software-Engineering/automation-exercise-wt2223#27]
[Automation Exercise Repository](https://github.com/musteng/automation-exercise-wt2223)

**Comment by uekerman** [comment]
Looks good except:

- Don't create the `.gitignore` file in the CI. Then, it is only a temporary file and will have no effect. Instead, you need to add and commit it to the repository.
- `black .`  directly formats. Use `black --check .` to only check the formatting.
