### ISSUE TITLE
[youssemk] Automation exercise

### ISSUE THREAD

**Issue by MarkAshraf96** [Simulation-Software-Engineering/automation-exercise-wt2223#31]
GitHub Repo: [https://github.com/MarkAshraf96/automation-exercise]( https://github.com/MarkAshraf96/automation-exercise)

**Comment by uekerman** [comment]
Looks good except:
 
- don't add temporary files such as `.DS_Store`
- misspelled `.gitignore`
- `black .` directly formats the code base. To only check the formatting use `black --check .` .
