### ISSUE TITLE
[hofmanjn] Automation exercise

### ISSUE THREAD

**Issue by bluzukk** [Simulation-Software-Engineering/automation-exercise-wt2223#4]
# GitHub Solution:
[https://github.com/bluzukk/automation-exercise](https://github.com/bluzukk/automation-exercise)

# GitLab Solution:
[https://gitlab-sim.informatik.uni-stuttgart.de/hofmanjn/automation-exercise](https://gitlab-sim.informatik.uni-stuttgart.de/hofmanjn/automation-exercise)

The GitLab Solution is a little rushed because I did not have much time this week:

```
# @TODO We do not need numpy, matplotlib, pytest, coverage and black in every job
before_script:
  - apt -yq update
  - apt -yq install software-properties-common
  - add-apt-repository ppa:deadsnakes/ppa
  - apt -yq update
  - export DEBIAN_FRONTEND="noninteractive" 
  - apt -yq install python3.11 python3-pip
  - pip install numpy matplotlib pytest coverage black
```

Feel free to restart the pipeline or push something to the GitLab Repo to start the jobs.
(My VM on bwCloud _should_ be running :smile:)

**Comment by uekerman** [comment]
Looks good :+1:
Enough to see that it did run at some point :grin:
